import "./globals.css";

export const metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container max-w-3xl my-20 bg-green-500">
          <div>{children}</div>
        </div>
        <script src="https://cdn.tailwindcss.com"></script>
      </body>
    </html>
  );
}
