import "./globals.css";

export const metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container flex justify-center items-center">
          <div className="max-w-3xl md:mx-10 mx-5">{children}</div>
        </div>
        <script src="https://cdn.tailwindcss.com"></script>
      </body>
    </html>
  );
}
